---
title: "615 final app"
author: "Ziyang Lin"
date: "2022-12-17"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(psych)
library(shiny)
library(leaflet)
library(mapsapi)
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
T2021Q4 <- read_csv("D:/615/final/LRTravelTimesQ4_21.csv")
T2022Q1 <- read_csv("D:/615/final/2022-Q1_LRTravelTimes.csv")
T2022Q2 <- read_csv("D:/615/final/2022-Q2_LRTravelTimes.csv")
T2022Q3 <- read_csv("D:/615/final/2022-Q3_LRTravelTimes.csv")
stops<-read_csv("D:/615/final/stops.csv")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
Tdata<-rbind(T2021Q4,T2022Q1,T2022Q2,T2022Q3)
Tdata$service_date<-as.Date(Tdata$service_date)
Tdata$month<-month(Tdata$service_date)
Tdata$week<-week(Tdata$service_date)
Tdata$weekdays<-weekdays(Tdata$service_date,abbreviate = T)

```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#Randomly choose 12 week in one year, 1 each month. Here I cited code from runze pang.
sample_weeks<-c()
set.seed(2119)
for (i in 1:12) {
  weeks_in_month<-levels(as.factor(Tdata$week[Tdata$month==i]))
  sample_weeks<-c(sample_weeks,sample(weeks_in_month[2:(length(weeks_in_month)-1)],1))
}

TweekD<-Tdata[Tdata$week %in% as.numeric(sample_weeks),]

TweekD$trip<-paste0(paste0("From ",TweekD$from_stop_id),paste0(" to ",TweekD$to_stop_id))

TweekD$trip<-as.factor(TweekD$trip)
```

```{r}
# Shiny App
stops<-stops[complete.cases(stops$stop_code),]
ui <- fluidPage(
  "I worked with Runze Pang to figure out the shiny here.",
  selectInput("trip", "Select a trip you are interested in ", choices = unique(TweekD$trip)),
  "Map below shows the trip(stops chosen) and alternative routes generated by google directions api. Distances and travel time are displayed as well. We could make comparisons of travel times between google direction api estimated and MBTA data produced.",
  
  
  "The stops.csv doesn't contain the lat-lon infomation for stop id = 70136,70137,70140,70141,70142 and 70143. So, errors will occur when choosing these stops for plotting.",
  leafletOutput("path"),
  textOutput("text"),
  "MBTA services are reliable since most of the routes' travel times are close.",
  selectInput("weekdays","Weekdays",choices = c("Mon","Tue","Wed","Thu","Fri","Sat","Sun")),
  
  "We picked days of the week as factors that might affect travel time. You can change the weekdays and see how it affects the histogram and the average travel time.",
  plotOutput("plot")
  
  
)



server <- function(input, output, session) {

  output$text<-renderText({
    mean_time<-round(mean(TweekD$travel_time_sec[TweekD$trip==input$trip & TweekD$weekdays==input$weekdays]),1)
    paste0("On ",input$weekdays, ", the average travel time between these two stations is ", mean_time," seconds.")
  }
  )
  
  output$plot<-renderPlot(hist(TweekD$travel_time_sec[TweekD$trip==input$trip & TweekD$weekdays==input$weekdays],main="Distribution of travel time",xlab="Travel time", breaks = 50))
  
  key = "AIzaSyDJD5tN-306IBoHQOQiiJ3JCICvnZa_iHw"
  
  

  
  output$path<-renderLeaflet({
    
    original_stop<-unique(TweekD$from_stop_id[TweekD$trip==input$trip])
    end_stop<-unique(TweekD$to_stop_id[TweekD$trip==input$trip])
    
    doc = mp_directions(
      origin = unlist(stops[stops$stop_code==original_stop,c(8,7)]),
      destination = unlist(stops[stops$stop_code==end_stop,c(8,7)]),
      mode = "transit",
      alternatives = TRUE,
      key = key,
      quiet = TRUE
    )
    
    routes = mp_get_routes(doc)
  
    leaflet() %>% addProviderTiles(provider = providers$CartoDB.Positron) %>%
                            addPolylines(data = routes, 
                                         opacity = 1, 
                                         weight = 7, 
                                         color = ~palette("R3"),
                                         label = ~paste0(distance_text," ",duration_s,"s"),
                                         labelOptions = labelOptions(noHide = TRUE))
  }
    )
  
}

shinyApp(ui = ui, server = server)
```

